sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf fluxunits.pdf --upload --lsstdoc fluxunits.tex --env=travis --ltd-product pstn-001"
env:
  global:
    - secure: "M6hfzzO7JKTOdBHpQAmYUk+csmJdXFzymLgfUDFgECFdilAk76HFIhbi1/LrHDJ3178woK7NJkJ7lp5kqxN1Lc8kgrd1ZD65U4AQPYiORJv7GP2KzYGy32kbNbZ4G7CQrwYwJNCrQZfPJ6YLdXD/NqzREoBTm2+FL505SvCj/hnaZHsEpVAf4FKncoUzZ82TMhxNPSirHqlTh0LnXnN+HCK30sa3NW9C+0CRPkgAmMD+W5oaCXrtnyBgblvnA6yR9UnZV09+TQ0Zv4JpOTeZYDBvelsbr/xp55LJ5kYfUGpvBRANYL3ArGMepaMXZmpopTpwrf7ReeEtiI7dv+GE6erzXxZx9aw9svF13DwClZRsLESWBLSGtA934NDlj7ZM0j8oIFhcdxcw3zN3C0EUSIkZ95fcliZcZqTy3uPRp0oCPPfbNigkT989XQ2anJ9IsVCu7A/HlAA5HBtjtxBH+vQ+6AtFllZJ5XV4dRj1MYst1LLFWD0AWUp3LSatoe/fdnCPuVuMlp5fYiXdE3z2/vMjR9vVk1VToxL/UolJlYj9H4CWZA0IJhQ5l0AaQ0Qg9LbvKecUkN5KH/rMoKX1SmLqmnZ7bMS1lmd8iHYPDgGZjjM2tIE1G6uZKZYAbtleHbaehBev6CUd2q876wRn7OPPaybwifxqFdEBXQBSN1s="
    - secure: "C+EJAhzRl+Onx5B+jKVP06o4KEYDilaogv445AMc9VqV4Is3wDVSysyqm3FtAKNrk4yGarHdBGQ7J10pgdUSaqwfIy5PAzC+MGgS3E3mOlJkUIbvM9H48NRALwrtVdILkQDZDrmWfKhPXocgTODKDk36mLyngGvpPcE2eaJ5C0mXPLo4uw9H8GUL3/OwThvOW+rVxIRPSVHaMeE37dM7QrWVnw/jnML4+/Gjnt5p750vV+hrrdj8flwM2GqiZhFuvvPkk6UZR2CuPO/OpuL09+hAbJ9L3xAKpfJG/09wZkpxM29hyBYeOZ4s1MFsNcmiKH01LqjlNHQdjp269E7n9BW2aJE5xpQlTTS2PVBjWY+U3ywY37sADHMF1uQSN73onWiL8MKf2TeNzR1QW3bo14rNMvuNzfEKDfiC5orgEnyxMPl6R3hfrOTAQTskS90PBzrJEg/2ShSEhid+KYXcJYcNXePsFwrRlyordtKwyzXk2j3dpusoTvPJkpSDX44M6xyBNdOYNjw6VspaDqkAld93AAFcFbAZ0L4kOQshS4nJ/nOFttRis9+Q8MkOPU8eMw90DkuI6iWVtU+ACGJTb/YpK7nLZwjUNKQGU8y9xb7WL1ntmtxhk+qFBrPBXHsfLIjHt0E1uKExDJyxkMrfEZ42wL5hm5mKctpsNhV66rk="
